### ISSUE TITLE
Խմբագրման միջավայրի և Տերմինալի տարօրինակ պահվածք

### ISSUE THREAD

**Issue by bugron** [LinguaCode/core#1]
Բարև Ձեզ: Նախ՝ շնորհակալություն նման կայք ստեղծելու համար: Հուսով եմ այն ակտիվ կօգտագործվի ծրագրավորման որոլտում նախնական գիտելիքներ ստանալու համար:

Մի քանի նրբություն, որ նկատեցի հենց առաջին անգամ կայքը բացելիս:
-  Թե՛ Խմբագրման միջավայրում, թե՛ Տերմինալում բացարձակ չի երևում թե ինչ է գրված:
  ![](http://i.prntscr.com/7913e7ddd4ee47a68dea243c7e05098c.png)
  Վերևի պատկերում իրոք տեքստ է գրված:
-  Խմբագրման միջավայրում ի սկզբանե (էջը բացելուց անմիջապես հետո) առկա տեքստը ևս չի երևում,
  ![](http://image.prntscr.com/image/09db1154416e4134b2c70ceaf96411a7.png)
  գրված է 
  
  ```
  տպել «Իմ անունը LinguaCode է, իսկ քո՞նը»
  գրել անուն
  տպել «հաճելի է ծանոթանալ, » + անուն
  ```
- Մեկնարկ կոճակը սեղմելուց հետո նույն բանը դիտվում է նաև Տերմինալ դաշտում՝
  ![](http://image.prntscr.com/image/79b728f9c84c4c098d791449dfee719f.png)
- Տերմինալ դաշտի պարունակությունը հնարավոր է ջնջել Delete կոճակով, բայց ոչ Backspace-ով (Խմբագրման միջավայր դաշտը նման թերություն չունի):

Ես հասկանում եմ, որ հայկական սովորությանը համաձայն նկարների բոլոր անկյուններում, երգերում, ծրագրերի կոդերի ամեն տողում պետք է նշել, թե ով է տվյալ ստեղծագործության հեղինակը, բայց դրա համար կա հատուկ ֆայլ, կոչվում է LICENSE, որի մասին Դուք արդեն տեղյակ եք: Հասկանում եք, Ձեր՝ այստեղ գրածը կարդալու են իմ նման մի քանի հոգի ու վերջ: Իսկ վերջնական սպառողը դրա մասին իմանում է սոցիալական ցանցերից, ֆորումներից, բլոգներից, իրենց ծանոթներից, հեռուստատեսությունից և այլն:

**Comment by otanim** [comment]
Հարգելի @bugron շնորհակալությունս եմ հայտնում նախաձեռնություն ցուցաբերելու եւ կամք դրսեւորելու օգնության համար։
Կայքը թեստավորվել է Chrome եւ FireFox բրաուզերների վերջին տարբերակներով (2016.05) եւ **Խմբագրման միջավայրում**՝

![image](https://cloud.githubusercontent.com/assets/7108843/15989699/e4949314-308f-11e6-912f-51f4b7aaf21a.png)
եւ Տերմինալում

![image](https://cloud.githubusercontent.com/assets/7108843/15989700/eea94246-308f-11e6-85f5-4341fcfc213e.png)

տեքստերի ինիցիալիզացիան տեղի է ունեցել հաջող։ Գուշակում եմ, որ հավանաբար այլ բրաուզերով եք բացել կայքը, որով դեռ չենք թեստավորել։
Սխալի ուղղման նպատակով կարո՞ղ եք նշել հետեւյալ տվյալները Ձեր համակարգչի վերաբերյալ․

- բրաուզերի անվանումը եւ տարբերակը,
- էկրանի չափսերը (պիքսելային),
- օպերացիոն համակարգի անվանումը։

Ինչ վերաբերում է նրան, որ բոլոր լոգիկա պարունակող ֆայլերում գրել եմ հեղինակի անվանումը, դա կատարել եմ 2 պատճառով, նախ նրա համար, որ դա JSDoc-ի ստանդարտներով ընդունելի երեւույթ է, եւ նախատեսում եմ բոլոր կոդերը փաստաթղթավորել, եւ եթե նկատել ես, որոշ պանակների ֆայլեր արդեն փաստաթղթավորված են։ Երկրորդ պատճառն այն է, որ որոշ անձինք, ովքեր ընդունակ լինելով սեփականը ստեղծել, զբաղվում են գաղափարագողությամբ, հեղինակային իրավունքների ոտնահարմամբ եւ շահի հետապնդմամբ։ Ունենալով նման մարդկանց հետ վատ փորձ, պահպանել եմ զգուշություն։

**Comment by bugron** [comment]
Օհ, իրոք մոռացել էի նշել այդ տվյալները: Խնդիրը դիտվում է Firefox 47.0-ում, ՕՀ-ս Windows 10 է, 1366x768: Chrome 50-ում նշված խնդիրը չկա:
Փաստաթղթավորել ասելով ես հասկանում եմ նկարագրել տվյալ կոդը, ոչ ամեն ֆայլում դնել ինիցիալները: Գողացողը որ ուզենա գողանալ, այդ ամենին միևնույնն է չի նայելու:

**Comment by otanim** [comment]
Կարծում եմ հավելյալ զգուշությունը չի խանգարի  :blush: , եւ դա նույնպես փաստաթղթավորման մի մաս է կազմում եւ կապ չունի հայկական մտածելակերպի դրսեւորման հետ։

@bugron շնորհակալություն տեղեկատվության եւ համագործակցության համար։ Կաշխատենք սխալը շուտով ուղղել։

**Comment by bugron** [comment]
@otanim շնորհակալություն օպերատիվության համար:

Իրականում Copyright-ի հետ կապված հարցը իմ կոմպետենտության շրջանակներից դուրս է, ուղղակի հետքրքիր էր, թե ինչու: Այնուամենայնիվ համարում եմ հայկական մտածելակերպի դրսեւորում, քանի որ դեպքերի բացարձակ մեծամասնությունում մերոնք են նման բան անում: Սա զուտ իմ անձնական կարծիքն է:

**Comment by otanim** [comment]
@bugron հասկանում եմ ինչի մասին ես ասում։ Սակայն ինչ վերաբերում է հայկական արտադրանքին, այն շատ սակավ է եւ մատնանշելը հեղինակային իրավունքները ոչ այդքան վատ երեւույթ։ Օրինակի համար, չէի իմանա, որ C9-ի կողմից գրված ACE խմբագրման միջավայրը, որ օգտագործվում է մի շարք կայքերում, ծրագրերում (այդ թվում՝ GitHub-ում եւ LinguaCode-ում), դրանց գլխավոր նախագծողներից մեկը հայ է ([Հարություն Ամիրջանյան](https://github.com/nightwing))։ Նմանատիպ տեղեկատվությունն ինձ միայն ուրախություն եւ հպարտություն է պատճառում։

**Comment by otanim** [comment]
@bugron ողջույն։
Ժամանակին որոշ ստուգումներ կատարելուց հետո համոզվեցի, որ խնդիրը կայանում էր **Firefox** բրաուզերի **45**-**48** տարբերակներում՝ կապված տառատեսակին ոչ ճիշտ երեւակման մեջ։ Այնուամենայնիվ ներկայիս **50.0** տարբերակում չի նկատվել ոչ մի խնդիր։
Թեստավորել հնարավոր է [այս հասցեով](https://linguacode.me/otanim/programs/authentication)։

Հ․Գ․ կայքը դեռ թեստավորման փուլում է։
